# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'   Returns a vector whose elements are the cumulative sums of the inputted
#'   numeric vector. The argument 'threshold' controls the max/min 
#'   ceiling/floor of the running sum before it is reset; i.e., if the 
#'   threshold is set to (+/-) Inf, one would, essentially, compute the base R 
#'   'cumsum', albeit much slower
#' 
#' @param x          A numeric vector
#' @param threshold  A numeric scalar specifying the cumulative 
#'                   threshold(reset)
cumsum_reset <- function(x, threshold) {
    .Call('_quanttools_cumsum_reset', PACKAGE = 'quanttools', x, threshold)
}

